spring:
  mail:
    host: smtp.gmail.com   # Dirección del servidor de correo saliente (SMTP)
    port: 587                # Puerto del servidor de correo saliente (587 para TLS, 465 para SSL)
    username: example@gmail.com # dirección de correo electrónico
    password: contraseña de aplicacion   #contraseña de correo electrónico
    properties:
      mail:
        smtp:
          auth: true           # Habilitar autenticación
          starttls:
            enable: true

  datasource:
    url: jdbc:h2:mem:amoxtlidb
    driver-class-name: org.h2.Driver