spring:
  mail:
    host: smtp.gmail.com   # Direcci贸n del servidor de correo saliente (SMTP)
    port: 587                # Puerto del servidor de correo saliente (587 para TLS, 465 para SSL)
    username: ${USERNAME_VAR} # direcci贸n de correo electr贸nico
    password: ${PASSWORD_VAR}
    properties:
      mail:
        smtp:
          auth: true           # Habilitar autenticaci贸n
          starttls:
            enable: true

  datasource:
    url: jdbc:h2:mem:amoxtlidb
    driver-class-name: org.h2.Driver
