name: Compila y libera el proyecto

on:
    release:
        types: [created]
    workflow_dispatch:

jobs:
  compilar:
    name: Compilar y liberar
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout proyecto
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: "17"
          cache: gradle

      - name: Setup frontend
        uses: ./.github/actions/setup-frontend
        with:
          node-version: 19
          pnpm-version: 8

      - name: Compilar frontend
        run: pnpm build
        working-directory: ./frontend

      - name: copiar archivos de frontend a backend
        run: |
          mkdir -p backend/src/main/resources/public
          cp -r ./frontend/dist/frontend/* backend/src/main/resources/public

      - name: Compilar backend
        run: ./gradlew bootJar
        working-directory: ./backend

      - run: |
          VERSION=$(./gradlew properties -q | awk '/^version:/ {print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo Version is $VERSION
        working-directory: ./backend

      - name: Copiar JAR a ubicación temporal
        run: |
          mkdir -p $GITHUB_WORKSPACE/tmp
          cp ./backend/build/libs/AmoxtliBackend-${{ env.VERSION }}.jar $GITHUB_WORKSPACE/tmp/AmoxtliBackend.jar

      - name: Iniciar sesión en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Instalar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Construir imagen y subir a Docker Hub
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/amoxtli-backend:latest
          build-args: |
            JAR_FILE=$GITHUB_WORKSPACE/tmp/AmoxtliBackend.jar
