name: Verificar backend

on:
  push:
    paths:
      - "backend/backend1/**"
  workflow_dispatch:

jobs:
  build:
    name: "Verificar backend"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout proyecto
        uses: actions/checkout@v3
      - name: Verificar
        uses: ./.github/actions/verificar-backend
        with:
            sonar-token: ${{ secrets.SONAR_TOKEN }}
            sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
            directorio: backend/backend1