name: Verificar backend

on:
  push:
    paths:
      - "backend/backend1"

jobs:
  build:
    name: "Verificar backend"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout proyecto
        uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: adopt
          java-version: 17
          cache: gradle

      - name: Ejecutar pruebas unitarias
        run: ./gradlew test