name: Verificar backend

on:
  push:
    paths:
      - "backend/**"
  workflow_dispatch:

jobs:
  build:
    name: "Verificar backend"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout proyecto
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Necesario para SonarQube
      - name: Verificar
        uses: ./.github/actions/verificar-backend
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            sonar-token: ${{ secrets.SONAR_TOKEN }}
            sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
            directorio: backend